---
title: "Códigos"
author: "Cesar Poggi"
date: '2022-09-11'
output: html_document
---
LEER Y GUARDAR DATOS
```{r}
Base100 = read_sav("Enaho01-2016-200.sav")
write_sav(Base100, "Enaho01-2021-100res.sav")
#Leer y guardar bases en .sav

write.csv(df,"C:\\Users\\Ron\\Desktop\\Test\\People.csv", row.names = FALSE)
#Guardar bases en csv
```


LIMPIAR DATOS
```{r}
MiembroFamilia$UBIGEO <- gsub("[[:space:]]","0",MiembroFamilia$VIVIENDA)
#Para reemplazar el espacio vacio u otro caracter con otro caracter

X20XXpan$P601A =trimws(X20XXpan$P601A,which=c("left"),whitespace = "[\\h\\v]")
#Para eliminar el espacio en blanco seleccionando si es al principio o final del string

X2021TODO01P1$P601B <- as.factor(X2021TODO01P1$P601B)
#Convertir variable a factor

levels(X2021TODO01P1$P601B) <- c("Si", "No")

X2021TODO01P1$P601A <- recode_factor(X2021TODO01P1$P601A, `0101` = "Pan Corriente o Comun", `0102` = "Pan Tolete", `0103` = "Pan Frances" , `0104` = "Pan Chapla" , `0105` = "Pan Integral" , `0106` = "Pan de Molde Envasado" , `0107` = "Pan de Yema")
#Agregar nombres a los niveles de un factor. Una opción te permite hacerlo de frente según el orden predeterminado. La segunda opción te permite especificar el nivel y ponerles un nombre específico.


label(X2021TODO01P1$P601B) = c("Obtuvo el producto")
#Cambiar la etiqueta de una variable
```

SELECCIONAR Y EXTRAER CARACTERES Y STRINGS
```{r}
X2006TODO01 = X20XXpan[grep("01..", X20XXpan$P601A, perl=TRUE),]
#Para seleccionar todos los casos que tengan "xx.." en una determinada variable. Los puntos representan cualquier caracter y se usan para determinar el orden en el que debe de estar los caracteres que sí se escriben. Si no se añaden los puntos, los caracteres sí escritos (en este caso xx) se identificarán de cualquier parte de un string.

panPRIMERO <- panPRIMERO %>%
  filter(P601B == 1)
#Para filtrar segun los valores de una columna

PANxFAM$UBIGEO2=substr(PANxFAM$UBIGEO, 1, 2)
#Para extraer los caracteres 1 y 2 de un string y ponerlos en otra columna

panPRIMERO$I601Z2 <- rowSums(panPRIMERO[,c("I601B2", "I601D2")], na.rm=TRUE)
#Para sumar filas en una nueva columna e ignorar los NAs considerandolos como 0
```

VER DATOS Y TABLAS EN BASE A CIERTOS CRITERIOS
```{r}
panPRIMERO[with(panPRIMERO, is.na(I601B2) & is.na(I601D2)),] 

panPRIMERO %>%
  filter(!if_all(c(I601B2, I601D2), is.na))
#Ver casos que tienen NA tanto en una variable como en otra, si agregamos un "!" antes del with hace lo contrario: aquellos que no tienen NA en ambas columnas (pero sí puede ser en una columna)

MiembroFamAGGRE = aggregate(P204 ~ CONGLOME + VIVIENDA + HOGAR, data = MiembroFamFILTR,sum)
#Para crear una table que haga un calculo estadistico (suma, media, variación, etc.) en base a una varaible que se pone primero y luego se ordena en base a las demas variables especificadas
```

```{r}
PANxFAM$DomEstr = ifelse(PANxFAM$DOM3 == "1" & PANxFAM$ESTRATO2 == "1", 1,
                         ifelse(PANxFAM$DOM3 == "1" & PANxFAM$ESTRATO2 == "2", 2,0))
#Condicionante Y de ifelse

PANxFAM$DOM3 = ifelse(PANxFAM$DOMINIO == "Sierra Centro" | PANxFAM$DOMINIO == "Sierra Sur", 2,0)
#Condicionante O de ifelse
```

MERGE Y PROBLEMAS RELACIONADOS AL MERGE
```{r}
PANxFAM=merge(PANxFAM, Base100, by = c("CONGLOME", "VIVIENDA", "HOGAR", "UBIGEO", "ESTRATO"))
#hacer merge de bases según varias columnas, también se puede usar argumentos como all.x, all.y, by.x, by.y

setdiff(PANxFAM,PANxFAM1)
#Para comprobar que filas hay en una base de datos que no hay en otra. Columnas deben ser iguales.
```

ESTADISTICAS CON PONDERACIÓN
```{r}
dessin1<- svydesign(id = ~1, #no clusters 
                      data = PANxFAM,
                      weight = ~FACTOR07)
#Para crear el diseño necesario para tbl_svysummary, en weights ponemos el factor de ponderación

datoF = tbl_svysummary(data= dessin1, by= DOMINIO, 
               include = c(I601Z2), 
               statistic = list(all_continuous() ~ "{mean} ({sd})"), #mediana y desviación
               digits = list(all_continuous() ~ c(2, 2)))

datoB = tbl_svysummary(data= dessin1.5, by= P601A, 
               include = c(P601B), 
               statistic = list(all_categorical() ~ "{n} ({p}%)"),#cantidad y porcentaje
               digits = list(P601B ~ c(0, 1)), missing = "no") #decimales específicados y sin missing
#Crear un objeto tbl_svysummary nos permite calcular diferentes estadisticos de una variable en base a un diseño de encuesta/ponderación que nos permite introducir un factor de ponderación que afectará a los casos y en base a este sacará los estadisticos que solicitemos. Ademas podemos cruzar con otra variable. Además podemos especificar la cantidad de decimales para cada uno de los estadísticos


datoC <- 
  dessin1.7 %>% 
  tbl_strata(
    strata = DOMINIO,
    .tbl_fun = 
      ~ .x %>% 
      tbl_svysummary(
        by = P601A,
        include = c(P601B),
        statistic = list(all_continuous() ~ "{mean} ({sd})"), 
        digits = list(all_continuous() ~ c(2, 2)), missing = "no"))
#Parte del paquete gtsummary nos permite crear una tabla estratificada por una categoria superior y otra por la cual se divide, además de permitirnos cruzar con otras variables.


datoB %>%
  as_flex_table() %>%
  flextable::save_as_docx(path = "C:\\Users\\Alejandro\\Desktop\\PULSO - Cuanti Desk\\Proyecto Panadería\\PANprimeroxConsumPerCapxDomEstr\\medidaspre2.docx")
#Para exportar una tabla gt_summary a un word
```
